apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: imghoard-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /images
        backend:
          serviceName: imghoard
          servicePort: 80